# Generated by Django 4.2.5 on 2023-10-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileMoneyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_created=True, auto_now=True)),
                ("created_at", models.DateTimeField(auto_created=True)),
                ("phone_number", models.CharField(max_length=9)),
                ("currency", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("reference", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("TF", "Failed"), ("TS", "Success")], max_length=2
                    ),
                ),
            ],
        ),
    ]
