# Generated by Django 2.2b1 on 2023-10-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_mobilemoneytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneytransaction',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mobilemoneytransaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
